name: "Verify nexus"
description: "Verify nexus files against imginfo"
inputs:
  filename:
    description: "nexus file to verify"
    required: true
    default: "test_nexus.nxs"
outputs:
  imginfo_exit_code:
    description: "imginfo_exit_code"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.filename }}
