apiVersion: v1
kind: Service
metadata:
  name: hyperion-svc
spec:
  type: LoadBalancer
  ports:
    - name: hyperion-api
      port: 5005
      protocol: TCP
      targetPort: 5005
  selector:
    app: hyperion
