# See https://confluence.diamond.ac.uk/x/tJqQC for instructions if this needs a new token
name: Assign author of pull request to referenced issue that was not assigned to issue ticket beforehand
run-name: ${{github.actor}} is learning GitHub Actions
on:   
 pull_request:
      types: [ready_for_review, opened, review_requested]
jobs:
  assign_pr_author_as_assignee:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        # This will get information about the project in general and add it to the environment.
        # * ISSUE_REFERENCED_ID - The ID for the Issue that was referenes at Fixes#999
        # * AUTHOR_ID - The ID of the person who made a pull request so that the author can be assigned to the Fixes#999
        env:
          GITHUB_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}
          ORGANIZATION: ${{ github.repository_owner }}
        run: |
          gh api graphql -f query='
            query ($org: String!, $number: Int!) {
              organization(login: $org!) {
                pullRequest(number: $number) {
                  closingIssuesReferences(first: 1) {
                    edges {
                      node {
                        id
                      }
                    }
                  }
                  author { ... on User {id} }
                }
              }
            }' -f org=$ORGANIZATION -f number=$PROJECT_NUMBER > project_data.json

          echo 'ISSUE_REFERENCED_ID='$(jq '.data.organization.pullRequest.closingIssuesReferences.edges.node.id' project_data.json) >> $GITHUB_ENV
          echo 'AUTHOR_ID='$(jq '.data.organization.pullRequest.author.id' project_data.json) >> $GITHUB_ENV
      # Add assingee of pull request of the references issue/ticket
      - name: Mutation to add name of pull request assigner to fixes ticket
        env:
          GITHUB_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}
        run: |
          gh api graphql -f query='
            mutation ($assignable_id: ID!, $author_id: [ID!]! ){
              addAssigneesToAssignable(input:{assignableId: $assignable_id, assigneeIds: $author_id })
              }' -f assignable_id=$ASSIGNABLE_ID -f author_id=$AUTHOR_ID --jq '.data.addAssigneesToAssignable')"

