name: Add new issues to project
on:
  issues:
    types:
      - opened
jobs:
  move_to_backlog:
    uses: ./.github/workflows/get_project_data.yml
    with:
      column_name: Backlog
      issue_id: ${{ github.event.issue.node_id }}
    secrets: inherit