# See https://confluence.diamond.ac.uk/x/tJqQC for instructions if this needs a new token
name: Add issues with rework to in progress
on:
  pull_request_review:
    types: [submitted]
jobs:
  get_associated_issue:
    uses: ./.github/workflows/get_issue_from_pr.yml
    with:
      pr_id: ${{ github.event.pull_request.number }}
    secrets: inherit
  move_to_in_progress_if_not_approved:
    needs: get_associated_issue
    if: github.event.review.state == 'CHANGES_REQUESTED'
    uses: ./.github/workflows/get_project_data_and_move_column.yml
    with:
      column_name: In Progress
      issue_id: ${{ needs.get_associated_issue.outputs.issue_from_pr }}
    secrets: inherit