global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: Artemis
    honor_timestamps: true
    scrape_interval: 15s
    static_configs:
      - targets:
          - localhost:12212
